/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poly.cafe.ui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.GraphicsEnvironment;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.JButton;
import poly.cafe.dao.BillDAO;
import poly.cafe.dao.CardDAO;
import poly.cafe.dao.impl.BillDAOImpl;
import poly.cafe.dao.impl.CardDAOImpl;
import poly.cafe.entity.Bill;
import poly.cafe.entity.Card;
import poly.cafe.ui.Controller.SalesController;

/**
 *
 * @author PC
 */
public class SalesJDialog extends javax.swing.JDialog implements SalesController {

    /**
     * Creates new form SalesJDialog
     */
    public SalesJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    @Override
    public void open() {
        this.setSize(700, 650); // Đặt kích thước 400x400
        this.setLocationRelativeTo(null);
        this.loadCards(); // tải và hiển thị các thẻ lên cửa sổ bán hàng 
    }

    @Override
    public void showBillJDialog(int cardId) { // Hiển thị cửa số phiếu bán hàng của thẻ 
        BillDAO dao = new BillDAOImpl();
        Bill bill = dao.findServicingByCardId(cardId); // tải bill đang phục vụ của thẻ 
        BillJDialog dialog = new BillJDialog((Frame) this.getOwner(), true);
        dialog.setBill(bill); // Cần khai báo vào BillJDialog @Setter Bill bill 
        dialog.setVisible(true);
    }

    private void loadCards() {
        CardDAO dao = new CardDAOImpl();
        List<Card> cards = dao.findAll();
        pnlCard.removeAll();
        cards.forEach(card -> pnlCard.add(this.createButton(card)));
        pnlCard.revalidate();
        pnlCard.repaint();
    }

    private JButton createButton(Card card) {
        JButton btnCard = new JButton();
        btnCard.setText(String.format("Card #%d", card.getId()));
        btnCard.setPreferredSize(new Dimension(0, 80));
        btnCard.setOpaque(true); // THÊM DÒNG NÀY
        btnCard.setContentAreaFilled(true); // VÀ DÒNG NÀY

        // Kiểm tra phiếu bán hàng đang phục vụ
        BillDAO billDAO = new BillDAOImpl();
        Bill servicingBill = billDAO.findServicingByCardId(card.getId());

        // Xác định trạng thái nút và màu nền
        boolean isEnabled = card.getStatus() == 0;
        btnCard.setEnabled(isEnabled);

        if (!isEnabled) {
            btnCard.setBackground(Color.GRAY); // Thẻ không hoạt động
        } else if (servicingBill == null) {
            btnCard.setBackground(Color.WHITE); // Thẻ hoạt động, chưa có bill
        } else {
            btnCard.setBackground(Color.GREEN); // Thẻ hoạt động, có bill đang phục vụ
        }

        btnCard.setActionCommand(String.valueOf(card.getId()));
        btnCard.addActionListener((ActionEvent e) -> {
            if (!btnCard.isEnabled()) {
                return;
            }
            int cardId = Integer.parseInt(e.getActionCommand());

            if (servicingBill != null) {
                // Đã có bill đang phục vụ, mở bill
                SalesJDialog.this.showBillJDialog(cardId);
            } else {
                // Chưa có bill, tự tạo
                Bill newBill = new Bill();
                newBill.setCardId(cardId);
                newBill.setUsername(poly.cafe.util.XAuth.user.getUsername());
                newBill.setCheckin(new java.util.Date());
                newBill.setStatus(0); // Đang phục vụ
                billDAO.create(newBill);

                // Sau khi tạo xong, load lại bill vừa tạo
                Bill createdBill = billDAO.findServicingByCardId(cardId);
                BillJDialog dialog = new BillJDialog((Frame) this.getOwner(), true);
                dialog.setBill(createdBill);
                dialog.setVisible(true);

                // Sau khi đóng, load lại danh sách cards (để update màu nền)
                this.loadCards();
            }
        });
        return btnCard;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCard = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bán hàng");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlCard.setLayout(new java.awt.GridLayout(0, 6, 5, 5));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCard, javax.swing.GroupLayout.DEFAULT_SIZE, 3, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.open();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SalesJDialog dialog = new SalesJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlCard;
    // End of variables declaration//GEN-END:variables
}
